app/views/report.py
from flask import Blueprint, redirect, render_template, session, url_for, request, jsonify
import sqlite3
from datetime import datetime, timedelta
from time import mktime

from app import app

report = Blueprint('report', __name__)

@report.before_request
def report_middleware():
    if not session.get("auth")=="Y":
        return redirect(url_for("auth.login"))
    if not session.get("role")=="admin":
        return redirect(url_for("dashboard.index"))  
    
@report.route("/report", methods=["GET"])
def index():
    start_date = (datetime.now() - timedelta(days=30)).strftime("%Y-%m-%d")
    end_date = datetime.now().strftime("%Y-%m-%d")

    return render_template("report.html", start_date=start_date, end_date=end_date)

@report.route("/report/data", methods=["GET", "POST"])
def data():
    start_date = request.form.get("start_date")
    end_date = request.form.get("end_date")

    start_date = int(mktime(datetime.strptime(start_date, '%Y-%m-%d').timetuple()))
    end_date = int(mktime((datetime.strptime(end_date, '%Y-%m-%d') + timedelta(days=1)).timetuple()))

    data = {
        "data": []
    }
    try:
        conn = sqlite3.connect(app.config["SQL"])
        cursor = conn.cursor()
        sql = f'''SELECT * FROM report WHERE created_date_int >={start_date} AND created_date_int<={end_date} ORDER BY created_date_int DESC'''
        cursor.execute(sql)
        records = cursor.fetchall()
        for key, value in enumerate(records):
            data["data"].append(
                {
                "id" : key+1,
                "motor": "motor "+str(value[3]),
                "squence": value[2],
                "user": value[1],
                "datetime": value[4]
                }
            )
    except Exception as err:
        pass

    return jsonify(data)

app/views/settings.py
from flask import Blueprint, redirect, render_template, request, url_for, session
import json

from app import app

settings = Blueprint("settings", __name__)

@settings.before_request
def settings_middleware():
    if not session.get("auth")=="Y":
        return redirect(url_for("auth.login"))
    if not session.get("role")=="admin":
        return redirect(url_for("dashboard.index")) 

@settings.route("/settings", methods=["GET"])
def index():
    settings = None
    with open(app.config["SETTINGS_PATH"]) as f:
        content = f.read()
        if content:
            settings = json.loads(content)
            order = []
            for i in range(1, 9):
                order.append(str(i))
                order.append(str(17-i))
            settings = {key: settings[key] for key in order}
            
                
    return render_template("settings.html", settings=settings)

@settings.route("/settings/editform", methods=["GET"])
def edit_form():
    index = request.args.get("index")
    settings = None
    if index:
        with open(app.config["SETTINGS_PATH"]) as f:
            content = f.read()
            if content:
                settings = json.loads(content)
        if settings:
            current_config = settings.get(str(index))
            if current_config: 
                not_available_relays = []
                not_available_pins = []
                for key, value in settings.items():
                    if(key!=str(index)):
                        not_available_relays.append(value["relay"])
                        not_available_pins.append(value["pin"])
                return render_template("settings_form.html", current_config=current_config, not_available_relays=not_available_relays, not_available_pins=not_available_pins)
    return "error"

@settings.route("/settings/edit", methods=["POST"])
def edit():
    response = {
        "status" : "",
        "message" : "",
    }

    if request.method=="POST":
        relay = request.form.get("relay") 
        pin = request.form.get("pin")
        buffer_time = request.form.get("buffer_time")
        position = request.form.get("position")

        settings = None
        with open(app.config["SETTINGS_PATH"], 'r') as f:
            content = f.read()
            if content:
                settings = json.loads(content)
        if settings is not None and settings.get(position) is not None:
            settings.get(position)["relay"] = int(request.form.get("relay")) if (request.form.get("relay")!="None") else request.form.get("relay")
            settings.get(position)["pin"] = int(request.form.get("pin")) if (request.form.get("pin")!="None") else request.form.get("pin")
            settings.get(position)["buffer_time"] = int(request.form.get("buffer_time"))
            content = json.dumps(settings)
            if content:
                with open(app.config["SETTINGS_PATH"], 'w') as f:
                    f.write(content)
                response["status"] = "success"
                response["message"] = "updated successfully"
                return response
            
    response["status"] = "error"
    response["message"] = "something went wrong, try again"

    return response

@settings.route("/settings/backup", methods=["GET"])
def backup():
    settings = None
    with open(app.config["BACKUP_SETTINGS_PATH"], 'r') as f:
        content = f.read()
        if content:
            settings = json.loads(content)
    if settings:
        with open(app.config["SETTINGS_PATH"], 'w') as f:
            f.write(json.dumps(settings))

    return "success"

app/views/users.py
from flask import render_template, request, url_for, redirect, Blueprint, jsonify, session
from datetime import datetime
import sqlite3

from app import app

users = Blueprint('users', __name__)

@users.before_request
def users_middleware():
    if not session.get("auth")=="Y":
        return redirect(url_for("auth.login"))
    if not session.get("role")=="admin":
        return redirect(url_for("dashboard.index"))        

@users.route("/users")
def index():
    users = []
    try:
        conn = sqlite3.connect(app.config["SQL"])
        cursor = conn.cursor()
        sql = f'SELECT * FROM users order by created_date desc'
        cursor.execute(sql)
        users = cursor.fetchall()
    except Exception as err:
        pass
    return render_template("users.html", users=users)

@users.route("/users/add", methods=["POST"])
def add():
    response = {
        "status" : "",
        "message" : "",
    }
    if request.method=="POST":
        username = request.form.get("username")
        password = request.form.get("password")
        message = ""
        error_flag = 0
        if(not (username!="" and len(username) > 2 and len(username) < 60)):
            error_flag = 1
            message = "Username is required and must be between 3 and 60 characters long. "
        if(not (password!="" and len(password) > 2 and len(password) < 60)):
            error_flag = 1
            message = message + "Password is required and must be between 3 and 60 characters long."

        if error_flag==1:
            response["status"] = "error"
            response["message"] = message
            return jsonify(response)
        else:
            try:
                conn = sqlite3.connect(app.config["SQL"])
                cursor = conn.cursor()
                sql = f'SELECT * FROM users WHERE username="{username}"'
                cursor.execute(sql)
                records = cursor.fetchall()
                if(not (len(records) > 0)):
                    sql = ''' INSERT INTO users(username, password, created_date, modified_date)
                             VALUES(?,?,datetime('now'),datetime('now')) '''
                    cursor.execute(sql, (username, password))
                    conn.commit()
                    response["status"] = "success"
                    response["message"] = "User added successfully"
                else:
                    response["status"] = "error"
                    response["message"] = f'user "{username}" already exist'
                conn.close()
            except Exception as err:
                print(err)
                response["status"] = "error"
                response["message"] = "Failed to add user"
    else:
        response["status"] = "error"
        response["message"] = "Failed to add user"
    return jsonify(response)


@users.route("/users/edit", methods=["POST"])
def edit():
    response = {
        "status" : "",
        "message" : "",
    }
    if request.method=="POST":
        username = request.form.get("username")
        password = request.form.get("password")

        message = ""
        error_flag = 0
        if(not (username!="" and len(username) > 2 and len(username) < 60)):
            error_flag = 1
            message = "Username is required and must be between 3 and 60 characters long. "
        if(not (password!="" and len(password) > 2 and len(password) < 60)):
            error_flag = 1
            message = message + "Password is required and must be between 3 and 60 characters long."

        if error_flag==1:
            response["status"] = "error"
            response["message"] = message
            return jsonify(response)
        else:
            try:
                conn = sqlite3.connect(app.config["SQL"])
                cursor = conn.cursor()
                sql = f'SELECT * FROM users WHERE username="{username}"'
                cursor.execute(sql)
                records = cursor.fetchall()
                if(len(records) > 0):
                    sql = '''UPDATE users SET password=?, modified_date=datetime('now') WHERE username=?'''
                    cursor.execute(sql, (password, username))
                    conn.commit()
                    response["status"] = "success"
                    response["message"] = "User updated successfully"
                else:
                    response["status"] = "error"
                    response["message"] = "User not found" 
                conn.close()
            except Exception as err:
                print(err)
                response["status"] = "error"
                response["message"] = "Failed to update user"
    else:
        response["status"] = "error"
        response["message"] = "Failed to update user"
    return jsonify(response)

@users.route("/users/delete/<username>", methods=["GET"])
def delete(username):
    try:
        conn = sqlite3.connect(app.config["SQL"])
        cursor = conn.cursor()
        sql = f'DELETE FROM users WHERE username="{username}"'
        cursor.execute(sql)
        conn.commit()
    except Exception as err:
        print(err)
        pass
    return redirect(url_for("users.index"))

    

app/templates/dashboard_error.html
{% extends 'layout.html' %}

{% block content %}
<h1>{{error}}</h1>
{% if error_type=="config" %}
<a href="{{ url_for('settings.index') }}">click here</a>
{% endif %}
<div id="message" class="d-block"></div>
{% endblock %}

{% block script %}
<script>
    $("#reset").on("click", function(){
        $.ajax({
            url: "{{url_for('dashboard.reset')}}",
            method: 'GET',
            beforeSend: function() {
                $("#message").replaceWith(`
                    <div id="message" class="alert alert-warning mb-2 flex-fill mx-2 rounded-0 d-flex flex-column" role="alert">
                        <p class="text-center mb-1">Please don't refresh the page before confirmation</p>
                        <div class="spinner-grow mx-auto" style="width: 3rem; height: 3rem;" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <p class="text-center">Waiting for confirmation...</p>
                    </div>
                `);
            },
            success: function(response) {
                if(response=="success"){
                    $("#message").replaceWith(`
                        <div id="message" class="alert alert-success mb-2 flex-fill mx-2 rounded-0 d-flex flex-column" role="alert">
                            <h1 class="text-center fs-1"><i class="bi bi-check2-circle"></i></h1>
                            <p class="text-center">Action successfull</p>
                            <p class="text-center">This page will auto-refresh in 2 seconds.</p>
                        </div>
                    `);
                    setTimeout(function(){
                        location.reload();
                    }, 2000);
                }else{
                    $("#message").replaceWith(`
                        <div id="message" class="alert alert-danger mb-2 flex-fill mx-2 rounded-0 d-flex flex-column" role="alert">
                            <h1 class="text-center fs-1"><i class="bi bi-x-circle"></i></h1>
                            <p class="text-center">Something went wrong please try again or refresh the page..</p>
                        </div>
                    `);
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
                $("#message").replaceWith(`
                        <div id="message" class="alert alert-danger mb-2 flex-fill mx-2 rounded-0 d-flex flex-column" role="alert">
                            <h1 class="text-center fs-1"><i class="bi bi-x-circle"></i></h1>
                            <p class="text-center">Something went wrong please try again or refresh the page..</p>
                        </div>
                `);
            }
        });
    });
</script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Motor control system</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-icons.css') }}">
    <style>
        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            padding: 56.67px 0 0;
            width: calc(2rem + 24px);
            z-index: 600;
            transition: all 500ms ease;
        }

        .sidebar.active {
            width: 240px;
        }
    
        .sidebar-sticky {
          position: relative;
          top: 0;
          height: calc(100vh - 48px);
          overflow-x: hidden;
          overflow-y: auto;
        }

        #sidebar-action-btn {
          transition: all 500ms ease;
        }
    
        #sidebar-action-btn.active {
          transform: rotate(180deg);
        }

        @media (max-width: 991.98px) {
          .sidebar {
            width: 100% !important;
          }
        }
    
        @media (min-width: 991.98px) {
          #main {
            padding-left: calc(2rem + 24px);
            transition: all 500ms ease;
          }

          header:has(> .sidebar.active) ~ #main{
            padding-left: 240px;
          }

          .sidebar:hover{
            width: 240px;
          }

          header:has(> .sidebar:hover) ~ #main{
            padding-left: 240px;
          }

        }
    </style>
    {% block style %}
    {% endblock %}
</head>
<body>
    <header>
        <nav id="sidebar" class="collapse navbar-collapse d-lg-block sidebar bg-white shadow">
            <div class="sidebar-sticky p-0">
                <div class="list-group list-group-flush">
                    <a href="{{url_for('dashboard.index')}}" class="d-flex align-items-center list-group-item list-group-item-action px-3 {% if request.path==url_for('dashboard.index') %}list-group-item-dark{% endif %}"  aria-current="true">
                        <i class="bi bi-columns-gap fs-4 me-3"></i>
                        <span>Dashboard</span>
                    </a>
                    {% if session.get('role')=="admin" %}
                    <a href="{{url_for('report.index')}}" class="d-flex align-items-center list-group-item list-group-item-action px-3"  aria-current="true">
                        <i class="bi bi-file-text fs-4 me-3"></i>
                        <span>Report</span>
                    </a>
                    <a href="{{url_for('users.index')}}" class="d-flex align-items-center list-group-item list-group-item-action px-3 {% if request.path==url_for('users.index') %}list-group-item-dark{% endif %}"  aria-current="true">
                        <i class="bi bi-people fs-4 me-3"></i>
                        <span>Users</span>
                    </a>
                    <a href="{{url_for('settings.index')}}" class="d-flex align-items-center list-group-item list-group-item-action px-3 {% if request.path==url_for('settings.index') %}list-group-item-dark{% endif %}"  aria-current="true">
                        <i class="bi bi-gear fs-4 me-3"></i>
                        <span>Settings</span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-expand-lg bg-white fixed-top border-bottom" style="min-height: 56.67px">
            <div class="container-fluid">
                <div class="ms-2">
                    <a class="navbar-brand fw-semibold me-2">Motor control system</a>
                    <button id="sidebar-action-btn" class="btn btn-outline-secondary border-0 p-1 py-0 d-none d-lg-inline">
                        <i class="bi bi-arrow-bar-right fs-5 fw-bold"></i>
                    </button>
                </div>
                <div class="me-2">
                    {% if request.path==url_for('dashboard.index') %}
                    <button id="reset" class="btn btn-outline-secondary">
                        <i class="bi bi-arrow-clockwise"></i>
                        Reset
                    </button>
                    {% endif %}
                    <form class="d-inline" action="{{ url_for('auth.logout') }}" method="POST">
                        <button class="btn btn-outline-secondary" type="submit">
                            <i class="bi bi-box-arrow-left"></i>
                            Logout
                        </button>
                    </form>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle sidebar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </div>
        </nav>
    </header>
    <main id="main" style="margin-top: 56.67px;">
        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $("#sidebar-action-btn").on('click', function(){
            $("#sidebar").toggleClass("active");
            $(this).toggleClass("active");
        });
    });
</script>
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
</script>
{% block script %}
{% endblock %}
</html>

app/templates/report.html
{% extends 'layout.html' %}

{% block style %}
<style>
    td{
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap5.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/daterangepicker.css') }}">

<div class="row mx-2 py-3">
    <div class="d-flex justify-content-center">
        <h1 class="mb-3">Report</h1>
        <div class="input-group mb-3 ms-auto" style="width: 16rem">
            <span class="input-group-text"><i class="bi bi-calendar2-event"></i></span>
            <input type="text" name="daterange" class="form-control datepicker" readonly>
        </div>
    </div>
    <div class="col-12">
        <table id="table" class="table border rounded mt-2">
            <thead>
                <tr>
                  <th class="text-center">#</th>
                  <th class="text-center">MOTOR</th>
                  <th class="text-center">SQUENCE</th>
                  <th class="text-center">USER</th>
                  <th class="text-center">DATE AND TIME</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/dataTables.bootstrap5.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/daterangepicker.min.js') }}"></script>

<script>
$(document).ready(function() {
    $(function() {
        $('.datepicker').daterangepicker({
            linkedCalendars: false,
            opens: "left",
            startDate: '{{start_date}}',
            endDate: '{{end_date}}',
            locale: {
                format: 'YYYY-MM-DD'
            },
            showDropdowns:true,
            minDate: '2023-01-01',
            maxDate:new Date(),
        });
    });

    $('.datepicker').on('apply.daterangepicker', function(ev, picker) {
        var start_date = picker.startDate.format('YYYY-MM-DD');
        var end_date = picker.endDate.format('YYYY-MM-DD');
        getData(start_date, end_date);
    });

    function getData(start_date, end_date){
        var table=$('#table').DataTable();
        table.destroy();
        $('#table tbody').empty();

        $('#table').DataTable( {
        "ordering": false,
        "lengthMenu": [ 10,25, 50, 75, 100 ],
        "ajax": {
            'url':"{{url_for('report.data')}}",
            'type':'POST',
            'data':{'start_date': start_date, 'end_date': end_date}
        },
        "serverside": true,
        "bPaginate": true,
        "bLengthChange": true,
        "bFilter": false,
        "bInfo": true,
        "bAutoWidth": true,
        columns: [
            {"data": "id"},
            {"data": "motor"},
            {"data": "squence"},
            {"data": "user"}, 
            {"data": "datetime"}                   
        ]
      });
    }

    getData('{{start_date}}', '{{end_date}}');
});

</script>
{% endblock %}

app/templates/settings.html
{% extends 'layout.html' %}

{% block content %}
<div class="row mx-2 py-3">
  <h1 class="mb-3">Settings</h1>
  <div class="col-12">
      <table class="table border rounded">
          <thead>
            <tr>
              <th class="text-center">#</th>
              <th class="text-center">MOTOR NAME</th>
              <th class="text-center">OPERATION MODE</th>
              <th class="text-center">RELAY</th>
              <th class="text-center">FEEDBACK</th>
              <th class="text-center">FEEDBACK PIN</th>
              <th class="text-center">BUFFER TIME</th>
              <th class="text-center">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% if settings is not none %}
              {% for key, value in settings.items() %}
              <tr>
                <td class="text-center">{{loop.index}}</td>
                <td class="text-center">{{"MOTOR "~value["index"]}}</td>
                {% if value["operation_mode"]==1 %}
                <td class="text-center">{{"FORWARD "~value["index"]}}</td>
                {% else %}
                <td class="text-center">{{"REVERSE "~value["index"]}}</td>
                {% endif %}
                <td class="text-center">{{value["relay"]}}</td>
                {% if value["feed_back"]==1 %}
                <td class="text-center">{{"FORWARD "~value["index"]}}</td>
                {% else %}
                <td class="text-center">{{"REVERSE "~value["index"]}}</td>
                {% endif %}
                <td class="text-center">{{value["pin"]}}</td>
                <td class="text-center">{{value["buffer_time"]}}</td>
                <td class="text-center"><button class="btn btn-secondary me-2 p-2 py-1 edit-form" data-index="{{key}}"><i class="bi bi-pencil-square" data-bs-toggle="tooltip" data-bs-title="Edit"></i></button></td>
              </tr>
              {% endfor %}
            {% endif %}
          </tbody>
      </table>
      <button id="reset" class="btn btn-outline-secondary ms-auto">Reset</button>
  </div>
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="editoffcanvas" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 id="offcanvas-title" class="offcanvas-title"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div id="editform" class="offcanvas-body">
  </div>
</div>
{% endblock %}

{% block script %}
<script>
  $("#reset").on("click", function(){
      $.ajax({
          url: "{{url_for('settings.backup')}}",
          method: 'GET',
          beforeSend: function() {
          },
          success: function(response) {
              if(response=="success"){
                  location.reload();
              }
          },
          error: function(jqXHR, textStatus, errorThrown) {
          }
      });
  });

  const bsOffcanvas = new bootstrap.Offcanvas('#editoffcanvas')
  $(".edit-form").on("click", function(){
    var index = $(this).attr("data-index");
    $.ajax({
      url: `{{url_for('settings.edit_form')}}?index=${index}`,
      method: "GET",
      success: function(response) {
        if(response!=="error"){
          $("#editform").html(response);
          bsOffcanvas.show();
        }else{
          console.log(response);
        }
      },  
      error: function(jqXHR, textStatus, errorThrown) {
        $("#alert").html(`<div class="alert alert-danger" role="alert">Something went wrong</div>`);
      }
    });
  });
</script>
{% endblock %}

app/templates/users.html
{% extends "layout.html" %}

{% block content %}
<div class="row mx-2 pt-3">
  <h1 class="mb-3">Users</h1>
  <div class="col-12">
      <table class="table border rounded">
          <thead>
            <tr>
              <th class="text-center">#</th>
              <th class="text-center">USERNAME</th>
              <th class="text-center">ACTION</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
              <tr>
                <td class="text-center">{{loop.index}}</td>
                <td class="text-center">{{user[1]}}</td>
                <td class="text-center"><button class="btn btn-secondary me-2 p-2 py-1" data-username="{{user[1]}}" data-password="{{user[2]}}" data-bs-toggle="offcanvas" data-bs-target="#usersoffcanvas" aria-controls="offcanvasRight" data-bs-title="Edit User" data-bs-action="{{ url_for('users.edit') }}" data-bs-type="edit"><i class="bi bi-pencil-square" data-bs-toggle="tooltip" data-bs-title="Edit"></i></button><a class="btn btn-danger p-2 py-1" href="{{ url_for('users.delete', username=user[1]) }}" ><i class="bi bi-trash" data-bs-toggle="tooltip" data-bs-title="Delete"></i></a></td>
              </tr>
            {% endfor %}
          </tbody>
      </table>
  </div>
  <div class="col-12 mt-4 p-0">
      <button class="btn btn-outline-secondary d-block ms-auto" data-bs-toggle="offcanvas" data-bs-target="#usersoffcanvas" aria-controls="offcanvasRight" data-bs-title="Add User" data-bs-action="{{ url_for('users.add') }}" data-bs-type="add">Add users</button>
  </div>
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="usersoffcanvas" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 id="offcanvas-title" class="offcanvas-title"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <form id="userform" method="POST">
      <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username">
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="text" class="form-control" id="password" name="password">
      </div>
      <button type="submit" class="btn btn-outline-secondary">Submit</button>
    </form>
    <div id="alert" class="mt-3"></div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
  $('[data-bs-toggle="offcanvas"]').on('click', function(){
    $('#offcanvas-title').html($(this).attr("data-bs-title"));
    $("#userform").attr("action", $(this).attr("data-bs-action"));
    if($(this).attr('data-bs-type')=="add"){
      $("#userform [name='username']").val("");
      $("#userform [name='password']").val("");
      $("#userform [name='username']").prop('readonly', false);
    }else{
      $("#userform [name='username']").val($(this).attr("data-username"));
      $("#userform [name='password']").val($(this).attr("data-password"));
      $("#userform [name='username']").prop('readonly', true);
    }
    $("#alert").html("");
  });
</script>
<script>
$(function() {
  $('#userform').submit(function(event) {
    event.preventDefault();
    var formData = $(this).serialize();
    var action = $(this).attr("action");
    $.ajax({
      url: action,
      method: 'POST',
      data: formData,
      success: function(response) {
        if(response.status=="success"){
          $("#alert").html(`<div class="alert alert-success" role="alert">${response.message}</div>`);
          setTimeout(function(){
            location.reload();
          }, 1000)
        }else{
          $("#alert").html(`<div class="alert alert-danger" role="alert">${response.message ? response.message : "Something went wrong"}</div>`);
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        $("#alert").html(`<div class="alert alert-danger" role="alert">Something went wrong</div>`);
      }
    });
  });
});

</script>
{% endblock %}